onetime-with-members/backend

.github/workflows/cicd.yml
Dockerfile
build.gradle
src/main/java/side/onetime/controller/TestConrtoller.java
src/main/java/side/onetime/global/config/SecurityConfig.java
src/main/resources/application.yml
src/test/java/side/onetime/OnetimeApplicationTests.java

---
- 일부 코드 수정
- 에러 해결
- CICD 구축
---
#1 
---

[Chore] : CICD 설정

---

.github/workflows/cicd.yml
src/main/java/side/onetime/domain/Event.java
src/main/java/side/onetime/domain/Member.java
src/main/java/side/onetime/domain/Schedule.java
src/main/java/side/onetime/global/common/ApiResponse.java
src/main/java/side/onetime/global/common/code/BaseCode.java
src/main/java/side/onetime/global/common/code/BaseErrorCode.java
src/main/java/side/onetime/global/common/constant/Category.java
src/main/java/side/onetime/global/common/constant/ErrorStatus.java
src/main/java/side/onetime/global/common/constant/SuccessStatus.java
src/main/java/side/onetime/global/common/dao/BaseEntity.java
src/main/java/side/onetime/global/common/dto/ErrorReasonDto.java
src/main/java/side/onetime/global/common/dto/ReasonDto.java
src/main/java/side/onetime/global/config/JpaConfig.java
src/main/java/side/onetime/repository/EventRepository.java
src/main/java/side/onetime/repository/MemberRepository.java
src/main/java/side/onetime/repository/ScheduleRepository.java

---
- 엔티티 세팅 완료
- 레포지토리 세팅 완료
---
#3 
---

[Feat] : 엔티티 세팅

---

src/main/java/side/onetime/domain/Member.java
src/main/java/side/onetime/domain/Schedule.java
src/main/java/side/onetime/domain/Selection.java
src/main/java/side/onetime/repository/SelectionRepository.java

---
- 엔티티 일부 컬럼 수정
- 선택 스케줄 도메인 추가
---
#3 
---

[Refactor] : 엔티티 일부 변경

---

src/main/java/side/onetime/controller/EventController.java
src/main/java/side/onetime/domain/Event.java
src/main/java/side/onetime/domain/Schedule.java
src/main/java/side/onetime/dto/EventDto.java
src/main/java/side/onetime/exception/EventErrorResult.java
src/main/java/side/onetime/exception/EventException.java
src/main/java/side/onetime/exception/GlobalExceptionHandler.java
src/main/java/side/onetime/global/common/constant/SuccessStatus.java
src/main/java/side/onetime/repository/EventRepository.java
src/main/java/side/onetime/service/EventService.java
src/main/java/side/onetime/util/DateUtil.java

---
- 이벤트 생성 API 구현
- 이벤트 조회 API 구현
---
#5 
---

[Feat] : 이벤트 생성 및 조회 API 구현

---

src/main/java/side/onetime/controller/MemberController.java
src/main/java/side/onetime/domain/Member.java
src/main/java/side/onetime/dto/MemberDto.java
src/main/java/side/onetime/exception/GlobalExceptionHandler.java
src/main/java/side/onetime/exception/MemberErrorResult.java
src/main/java/side/onetime/exception/MemberException.java
src/main/java/side/onetime/global/common/constant/SuccessStatus.java
src/main/java/side/onetime/repository/MemberRepository.java
src/main/java/side/onetime/service/MemberService.java

---
- 멤버 로그인 API 구현
- 멤버 이름 중복 확인 API 구현
---
#8 
---

[Feat] : 멤버 로그인 & 중복 확인 API 구현

---

src/main/java/side/onetime/controller/ScheduleController.java
src/main/java/side/onetime/dto/MemberDto.java
src/main/java/side/onetime/dto/ScheduleDto.java
src/main/java/side/onetime/exception/GlobalExceptionHandler.java
src/main/java/side/onetime/exception/ScheduleErrorResult.java
src/main/java/side/onetime/exception/ScheduleException.java
src/main/java/side/onetime/global/common/constant/SuccessStatus.java
src/main/java/side/onetime/repository/MemberRepository.java
src/main/java/side/onetime/repository/ScheduleRepository.java
src/main/java/side/onetime/repository/SelectionRepository.java
src/main/java/side/onetime/service/EventService.java
src/main/java/side/onetime/service/MemberService.java
src/main/java/side/onetime/service/ScheduleService.java

---
- 요일 스케줄 등록 API 구현
- 날짜 스케줄 등록 API 구현
---
#9 
---

[Feat] : 요일 & 날짜 스케줄 등록 API 구현

---

src/main/java/side/onetime/controller/ScheduleController.java
src/main/java/side/onetime/dto/ScheduleDto.java
src/main/java/side/onetime/exception/GlobalExceptionHandler.java
src/main/java/side/onetime/exception/MemberErrorResult.java
src/main/java/side/onetime/exception/SelectionErrorResult.java
src/main/java/side/onetime/exception/SelectionException.java
src/main/java/side/onetime/global/common/constant/SuccessStatus.java
src/main/java/side/onetime/repository/MemberRepository.java
src/main/java/side/onetime/repository/SelectionRepository.java
src/main/java/side/onetime/service/ScheduleService.java

---
- 전체 & 개인 요일 스케줄 조회
- 전체 & 개인 날짜 스케줄 조회
---
#9 
---

[Feat] : 스케줄 조회 API 구현

---

src/main/java/side/onetime/dto/EventDto.java
src/main/java/side/onetime/dto/ScheduleDto.java

---
- 응답 형식 통일을 위해 @JsonProperty 사용
---
#9 
---

[Refactor] : 요일 & 날짜 스케줄 응답 형식 통일

---

src/main/java/side/onetime/controller/MemberController.java
src/main/java/side/onetime/dto/MemberDto.java
src/main/java/side/onetime/exception/MemberErrorResult.java
src/main/java/side/onetime/global/common/constant/SuccessStatus.java
src/main/java/side/onetime/repository/MemberRepository.java
src/main/java/side/onetime/service/MemberService.java

---
- 멤버 등록 & 로그인 로직 분리
- 멤버 등록 API 구현
---
#15 
---

[Refactor] : 멤버 등록 관련 리팩토링 완료

---

src/main/java/side/onetime/controller/EventController.java
src/main/java/side/onetime/dto/EventDto.java
src/main/java/side/onetime/global/common/constant/SuccessStatus.java
src/main/java/side/onetime/repository/SelectionRepository.java
src/main/java/side/onetime/service/EventService.java

---
- 가장 많이 되는 시간 조회 API 구현
- fetch join 사용하여 성능 개선 (3초 -> 0.3초)
---
#5 
---

[feat] : 가장 많이 되는 시간 조회 API 구현

---

src/main/java/side/onetime/exception/EventErrorResult.java
src/main/java/side/onetime/service/EventService.java

---
- 날짜 or 요일 이벤트가 구분 되지 않던 문제를 해결함
---
#18 
---

[fix] : 날짜 or 요일 이벤트 구분되지 않던 문제 해결

---

src/main/java/side/onetime/service/EventService.java
src/main/java/side/onetime/util/DateUtil.java

---
- 날짜 & 요일 정렬되지 않던 문제 해결
- 정렬 메서드 추가
---
#18 
---

[fix] : 날짜 & 요일 정렬되지 않던 문제 해결

---

src/main/java/side/onetime/domain/Event.java

---
- 컬럼 사이즈를 변경하였습니다.
---
#18 
---

[refactor] : 이벤트 제목 컬럼 사이즈 변경

---

src/main/java/side/onetime/controller/ScheduleController.java
src/main/java/side/onetime/dto/ScheduleDto.java
src/main/java/side/onetime/global/common/constant/SuccessStatus.java
src/main/java/side/onetime/repository/MemberRepository.java
src/main/java/side/onetime/service/ScheduleService.java

---
- 멤버 필터링 요일 & 날짜 조회 API를 구현하였습니다.
---
#24 
---

[feat] : 멤버 필터링 조회 API 구현

---

src/main/java/side/onetime/controller/UrlController.java
src/main/java/side/onetime/dto/UrlDto.java
src/main/java/side/onetime/global/common/constant/SuccessStatus.java
src/main/java/side/onetime/service/EventService.java
src/main/java/side/onetime/service/UrlService.java
src/main/java/side/onetime/util/Base62Util.java
src/main/java/side/onetime/util/DateUtil.java

---
- 유틸 클래스는 static 메서드로 변경한다.
- URL 단축 기능을 구현한다.
---
- Resolves : #23 
---

[feat] : URL 단축 기능을 구현한다

---

.github/workflows/cicd.yml
src/main/resources/application.yml

---
- 환경변수명 변경
- GCP를 기준으로 CICD 파이프라인을 변경
---
- Resolves : #28 
---

[chore] : NCP -> GCP로 서버를 이전한다

---

src/main/java/side/onetime/util/Base62Util.java

---
- 단축 URL 도메인을 변경한다
---
- Resolves : #30 
---

[refactor] : 단축 URL 도메인을 변경한다

---

build.gradle
src/main/java/side/onetime/auth/constant/Provider.java
src/main/java/side/onetime/auth/dto/GoogleUserInfo.java
src/main/java/side/onetime/auth/dto/KakaoUserInfo.java
src/main/java/side/onetime/auth/dto/NaverUserInfo.java
src/main/java/side/onetime/auth/dto/OAuth2UserInfo.java
src/main/java/side/onetime/auth/handler/OAuthLoginFailureHandler.java
src/main/java/side/onetime/auth/handler/OAuthLoginSuccessHandler.java
src/main/java/side/onetime/controller/TokenController.java
src/main/java/side/onetime/controller/UserController.java
src/main/java/side/onetime/domain/RefreshToken.java
src/main/java/side/onetime/domain/User.java
src/main/java/side/onetime/dto/TokenDto.java
src/main/java/side/onetime/dto/UserDto.java
src/main/java/side/onetime/exception/GlobalExceptionHandler.java
src/main/java/side/onetime/exception/TokenErrorResult.java
src/main/java/side/onetime/exception/TokenException.java
src/main/java/side/onetime/exception/UserErrorResult.java
src/main/java/side/onetime/exception/UserException.java
src/main/java/side/onetime/global/common/constant/SuccessStatus.java
src/main/java/side/onetime/global/config/SecurityConfig.java
src/main/java/side/onetime/repository/RefreshTokenRepository.java
src/main/java/side/onetime/repository/UserRepository.java
src/main/java/side/onetime/service/TokenService.java
src/main/java/side/onetime/service/UserService.java
src/main/java/side/onetime/util/JwtUtil.java
src/main/resources/application.yml

---
- 구글 소셜 로그인 기능을 구현하였습니다.
- 카카오 소셜 로그인 기능을 구현하였습니다.
- 네이버 소셜 로그인 기능을 구현하였습니다.
---
- Resolves : #32 
---
추후 실패 시 리다이렉트 처리 추가 필요함

[feat] : 소셜 로그인 기능을 구현한다

---

src/main/java/side/onetime/repository/EventRepository.java
src/main/java/side/onetime/service/UrlService.java
src/main/java/side/onetime/util/Base62Util.java

---
- URL 변환 시 검증 로직을 추가한다
---
- Resolves : #34 
---

[feat] : URL 변환 시 검증 로직을 추가한다

---

src/main/java/side/onetime/global/config/SecurityConfig.java

---
- 허용 Orgin을 지정한다
---
- Ref : #39 
---

[chore] : 허용 Orgin을 지정한다

---

src/main/java/side/onetime/global/config/SecurityConfig.java

---
- CORS 문제를 해결한다
---
- Resolves : #43 
---

[fix] : CORS 문제를 해결한다

---

src/main/java/side/onetime/auth/handler/OAuthLoginSuccessHandler.java

---
- 온보딩 시 소셜 계정 이름을 확인할 수 있다
---
- Resolves : #36 
---

[feat] : 온보딩 시 소셜 계정 이름을 확인할 수 있다

---

src/main/java/side/onetime/auth/handler/OAuthLoginSuccessHandler.java
src/main/java/side/onetime/controller/UserController.java
src/main/java/side/onetime/domain/User.java
src/main/java/side/onetime/dto/UserDto.java
src/main/java/side/onetime/exception/UserErrorResult.java
src/main/java/side/onetime/global/common/constant/SuccessStatus.java
src/main/java/side/onetime/service/UserService.java
src/main/java/side/onetime/util/JwtUtil.java

---
- 유저에 이메일 정보 추가
- 유저 정보 조회 API 구현
- 유저 정보 수정 API 구현
---
- Resolves : #37 
---

[feat] : 마이페이지에서 유저 정보를 확인 및 수정할 수 있다

---

src/main/java/side/onetime/global/config/SecurityConfig.java

---
- 단축 URL 도메인 CORS 문제를 해결한다
---
- Resolves : #50 
---

[fix] : 단축 URL 도메인 CORS 문제를 해결한다

---

src/main/java/side/onetime/controller/EventController.java
src/main/java/side/onetime/controller/ScheduleController.java
src/main/java/side/onetime/domain/Event.java
src/main/java/side/onetime/domain/Selection.java
src/main/java/side/onetime/domain/User.java
src/main/java/side/onetime/repository/SelectionRepository.java
src/main/java/side/onetime/service/EventService.java
src/main/java/side/onetime/service/ScheduleService.java

---
- 로그인 유저가 이벤트 생성 & 스케줄 등록을 할 수 있다
---
- Resolves : #52 
---

[feat] : 로그인 유저가 이벤트 생성 & 스케줄 등록을 할 수 있다

---

src/main/java/side/onetime/domain/Event.java
src/main/java/side/onetime/domain/EventParticipation.java
src/main/java/side/onetime/domain/User.java
src/main/java/side/onetime/domain/enums/EventStatus.java
src/main/java/side/onetime/exception/GlobalExceptionHandler.java
src/main/java/side/onetime/repository/EventParticipationRepository.java
src/main/java/side/onetime/repository/UserRepository.java
src/main/java/side/onetime/service/EventService.java
src/main/java/side/onetime/service/ScheduleService.java

---
- 이벤트 생성 및 참여 시 이벤트 참여여부에 저장된다
---
---

[feat] : 이벤트 생성 및 참여 시 이벤트 참여여부에 저장된다

---

src/main/java/side/onetime/controller/UserController.java
src/main/java/side/onetime/domain/User.java
src/main/java/side/onetime/dto/EventDto.java
src/main/java/side/onetime/global/common/constant/SuccessStatus.java
src/main/java/side/onetime/service/UserService.java

---
- 유저는 서비스를 탈퇴할 수 있다
---
- Resolves : #48 
---

[feat] : 유저는 서비스를 탈퇴할 수 있다

---

src/main/java/side/onetime/dto/EventDto.java
src/main/java/side/onetime/service/EventService.java

---
- 유저 참여 이벤트 목록 조회 시 가장 많이 되는 시간 목록도 반환한다
---
- Resolves : #62 
---

[feat] : 유저 참여 이벤트 목록 조회 시 가장 많이 되는 시간 목록도 반환한다

---

src/main/java/side/onetime/controller/EventController.java
src/main/java/side/onetime/controller/MemberController.java
src/main/java/side/onetime/controller/ScheduleController.java
src/main/java/side/onetime/controller/TokenController.java
src/main/java/side/onetime/controller/UrlController.java
src/main/java/side/onetime/controller/UserController.java
src/main/java/side/onetime/domain/Event.java
src/main/java/side/onetime/domain/enums/Category.java
src/main/java/side/onetime/dto/EventDto.java
src/main/java/side/onetime/exception/GlobalExceptionHandler.java
src/main/java/side/onetime/global/common/constant/Category.java
src/main/java/side/onetime/global/common/status/ErrorStatus.java
src/main/java/side/onetime/global/common/status/SuccessStatus.java
src/main/java/side/onetime/service/EventService.java
src/main/java/side/onetime/service/MemberService.java
src/main/java/side/onetime/util/DateUtil.java

---
- 패키지 이동 및 이름을 변경한다
---
- Resolves : #65 
---

[refactor] : 패키지 이동 및 이름을 변경한다

---

src/main/java/side/onetime/auth/handler/OAuthLoginSuccessHandler.java
src/main/java/side/onetime/exception/TokenErrorResult.java
src/main/java/side/onetime/service/TokenService.java
src/main/java/side/onetime/service/UserService.java
src/main/java/side/onetime/util/JwtUtil.java
src/main/resources/application.yaml

---
- 레지스터 토큰 유효기간 지정
- 에러 처리 추가
---
- Resolves : #67 
---

[feat] : 레지스터 토큰 유효기간을 지정한다

---

src/main/java/side/onetime/util/JwtUtil.java

---
- 만료된 토큰에 대한 에러 처리가 잘 되도록 유효 검증을 추가함
---
- Resolves : #69 
---

[feat] : 토큰 유효 검증을 추가한다

---

src/main/java/side/onetime/exception/TokenErrorResult.java
src/main/java/side/onetime/repository/RefreshTokenRepository.java
src/main/java/side/onetime/service/TokenService.java

---
- 리프레쉬 토큰 제한 개수 지정
- 제한 개수 넘어갈 시 에러 처리
---
- Resolves : #71 
---

[feat] : 리프레쉬 토큰 제한 개수를 지정한다

---

src/main/java/side/onetime/controller/EventController.java
src/main/java/side/onetime/domain/Event.java
src/main/java/side/onetime/domain/Member.java
src/main/java/side/onetime/domain/Schedule.java
src/main/java/side/onetime/domain/User.java
src/main/java/side/onetime/exception/EventParticipationErrorResult.java
src/main/java/side/onetime/exception/EventParticipationException.java
src/main/java/side/onetime/exception/GlobalExceptionHandler.java
src/main/java/side/onetime/global/common/status/SuccessStatus.java
src/main/java/side/onetime/service/EventService.java

---
- 유저는 생성한 이벤트를 삭제할 수 있다
---
- Resolves : #75 
---

[feat] : 유저는 생성한 이벤트를 삭제할 수 있다

---

build.gradle
src/main/java/side/onetime/domain/Event.java
src/main/java/side/onetime/domain/Member.java
src/main/java/side/onetime/domain/Schedule.java
src/main/java/side/onetime/domain/User.java
src/main/java/side/onetime/global/config/QueryDslConfig.java
src/main/java/side/onetime/repository/EventRepository.java
src/main/java/side/onetime/repository/custom/EventRepositoryCustom.java
src/main/java/side/onetime/repository/custom/EventRepositoryImpl.java
src/main/java/side/onetime/service/EventService.java

---
- 쿼리 DSL 기능을 추가한다
---
- Resolves : #78 
---

[feat] : 쿼리 DSL 기능을 추가한다

---

src/main/java/side/onetime/global/config/SchedulerConfig.java
src/main/java/side/onetime/repository/EventRepository.java
src/main/java/side/onetime/repository/custom/EventRepositoryCustom.java
src/main/java/side/onetime/repository/custom/EventRepositoryImpl.java
src/main/java/side/onetime/service/EventCleanupScheduler.java
src/main/java/side/onetime/service/EventService.java
src/main/resources/application.yaml

---
- 특정 시기마다 30일이 지난 이벤트들을 제거할 수 있다
---
- Resolves : #76 
---

[feat] : 특정 시기마다 30일이 지난 이벤트들을 제거할 수 있다

---

src/main/java/side/onetime/dto/event/request/CreateEventRequest.java

---
- Enum은 `@NotNull`로 변경하여 문제를 해결한다
---
- Resolves : #88 
---

[fix] : Enum은 @NotNull로 변경하여 문제를 해결한다

---

src/main/java/side/onetime/controller/FixedController.java
src/main/java/side/onetime/dto/fixed/response/FixedEventDetailResponse.java
src/main/java/side/onetime/dto/fixed/response/FixedEventResponse.java
src/main/java/side/onetime/exception/status/FixedErrorStatus.java
src/main/java/side/onetime/global/common/status/SuccessStatus.java
src/main/java/side/onetime/repository/custom/FixedEventRepositoryCustom.java
src/main/java/side/onetime/repository/custom/FixedEventRepositoryImpl.java
src/main/java/side/onetime/service/FixedScheduleService.java

---
- 유저는 마이페이지에서 고정 스케줄을 상세 조회할 수 있다
---
---

[feat] : 유저는 마이페이지에서 고정 스케줄을 상세 조회할 수 있다

---

src/main/java/side/onetime/controller/FixedController.java
src/main/java/side/onetime/domain/FixedEvent.java
src/main/java/side/onetime/dto/fixed/request/ModifyFixedEventRequest.java
src/main/java/side/onetime/global/common/status/SuccessStatus.java
src/main/java/side/onetime/repository/FixedEventRepository.java
src/main/java/side/onetime/repository/FixedSelectionRepository.java
src/main/java/side/onetime/repository/custom/FixedEventRepositoryCustom.java
src/main/java/side/onetime/repository/custom/FixedEventRepositoryImpl.java
src/main/java/side/onetime/repository/custom/FixedSelectionRepositoryCustom.java
src/main/java/side/onetime/repository/custom/FixedSelectionRepositoryImpl.java
src/main/java/side/onetime/service/FixedEventService.java
src/main/java/side/onetime/service/FixedScheduleService.java

---
- 유저는 마이페이지에서 고정 스케줄을 수정할 수 있다
---
---

[feat] : 유저는 마이페이지에서 고정 스케줄을 수정할 수 있다

---

src/main/java/side/onetime/controller/FixedController.java
src/main/java/side/onetime/global/common/status/SuccessStatus.java
src/main/java/side/onetime/repository/FixedEventRepository.java
src/main/java/side/onetime/repository/custom/FixedEventRepositoryCustom.java
src/main/java/side/onetime/repository/custom/FixedEventRepositoryImpl.java
src/main/java/side/onetime/service/FixedEventService.java
src/main/java/side/onetime/service/FixedScheduleService.java

---
- 유저는 마이페이지에서 고정 스케줄을 삭제할 수 있다
---
- Resolves : #90 
---

[feat] : 유저는 마이페이지에서 고정 스케줄을 삭제할 수 있다

---

src/main/java/side/onetime/domain/User.java

---
- 신규 유저 등록 과정에서, 동시성 문제 발생으로 인해 동일한 유저의 데이터가 6개가 삽입됨
- 다행히 이 중 가장 마지막에 삽입된 유저 데이터로 서비스 이용 자체는 되었던 것 같음
- 허나 앞으로를 고려하면 큰 문제가 될 수 있을 것 같아 해결하기로 결정함
- 유저는 providerId를 기준으로 고유함을 판단하기 때문에, 해당 컬럼에 UK를 설정하여 해결함
---
- Resolves : #100 
---
동시성 문제에 대해 조금 더 공부해 보고 대비해 보아야겠다 🧑🏻‍💻🔥

[fix] : UK를 설정하여 동시성 문제를 해결한다

---

src/main/java/side/onetime/controller/EventController.java
src/main/java/side/onetime/dto/event/response/GetEventResponse.java
src/main/java/side/onetime/dto/event/response/GetUserParticipatedEventsResponse.java
src/main/java/side/onetime/service/EventService.java

---
- 로그인 유저 대상, 이벤트 조회 시 이벤트 참여 상태도 반환한다
---
- Resolves : #103 
---

[feat] : 로그인 유저 대상, 이벤트 조회 시 이벤트 참여 상태도 반환한다

---

src/main/java/side/onetime/service/FixedScheduleService.java

---
- 고정 스케줄을 한 번도 등록하지 않은 유저에 대해 발생하는 문제를 해결한다
---
- Resolves : #105 
---

[fix] : 고정 스케줄을 한 번도 등록하지 않은 유저에 대해 발생하는 문제를 해결한다

---

.github/workflows/dev-cicd.yml
.github/workflows/test-cicd.yml
build.gradle
src/main/java/side/onetime/global/common/status/ErrorStatus.java
src/main/java/side/onetime/global/config/SwaggerConfig.java
src/main/resources/static/docs/open-api-3.0.1.json

---
---
- Resolves : #112 
---

[feat] : REST Docs & Swagger 설정을 추가한다

---

src/main/java/side/onetime/global/config/SwaggerConfig.java
src/main/resources/application.yaml
src/test/java/side/onetime/configuration/ControllerTestConfig.java
src/test/java/side/onetime/event/EventControllerTest.java

[feat] : Event API 테스트 코드를 작성한다

---

src/main/java/side/onetime/global/common/status/SuccessStatus.java
src/main/resources/application.yaml
src/test/java/side/onetime/fixed/FixedControllerTest.java
src/test/java/side/onetime/member/MemberControllerTest.java
src/test/java/side/onetime/schedule/ScheduleControllerTest.java
src/test/java/side/onetime/token/TokenControllerTest.java
src/test/java/side/onetime/url/UrlControllerTest.java
src/test/java/side/onetime/user/UserControllerTest.java

---
---
- Resolves : #114 
---

[feat] : 각 도메인에 대한 테스트 코드를 작성하여 API 문서화를 진행한다

---

src/main/java/side/onetime/controller/EventController.java
src/main/java/side/onetime/controller/FixedController.java
src/main/java/side/onetime/controller/MemberController.java
src/main/java/side/onetime/controller/ScheduleController.java
src/main/java/side/onetime/controller/TokenController.java
src/main/java/side/onetime/controller/UrlController.java
src/main/java/side/onetime/controller/UserController.java

---
```java
...
/**
* 유저 온보딩 API
*
* 회원가입 이후, 유저의 닉네임을 설정하고 온보딩을 완료하는 API입니다.
* 주어진 레지스터 토큰을 통해 사용자 정보를 확인한 후, 액세스 토큰과 리프레쉬 토큰을 발급하여 반환합니다.
*
* @param onboardUserRequest 유저의 레지스터 토큰과 닉네임 정보를 포함하는 요청 객체
* @return 발급된 액세스 토큰과 리프레쉬 토큰을 포함하는 응답 객체
*/
@PostMapping("/onboarding")
public ResponseEntity<ApiResponse<OnboardUserResponse>> onboardUser(
@Valid @RequestBody OnboardUserRequest onboardUserRequest) {
OnboardUserResponse onboardUserResponse = userService.onboardUser(onboardUserRequest);
return ApiResponse.onSuccess(SuccessStatus._ONBOARD_USER, onboardUserResponse);
}
...
```
---
- Resolves : #115 
---

[style] : 주석을 추가하여 도메인 별 API들의 설명을 구체화한다

---

build.gradle
src/main/java/side/onetime/controller/EventController.java
src/main/java/side/onetime/domain/Event.java
src/main/java/side/onetime/dto/event/response/GetEventQrCodeResponse.java
src/main/java/side/onetime/exception/status/EventErrorStatus.java
src/main/java/side/onetime/global/common/status/SuccessStatus.java
src/main/java/side/onetime/global/config/S3Config.java
src/main/java/side/onetime/service/EventService.java
src/main/java/side/onetime/util/FileUtil.java
src/main/java/side/onetime/util/QrUtil.java
src/main/java/side/onetime/util/S3Util.java
src/main/resources/application.yaml
src/test/java/side/onetime/event/EventControllerTest.java

---
- 이벤트 생성 시, QR Code를 생성하여 s3에 저장합니다.
- 이후 조회 API를 통해 이벤트로 이동할 수 있는 QR Code 이미지를 받아올 수 있습니다.
---
- Resolves : #127 
---

[feat] : 각 이벤트의 QR 코드를 생성하고 조회할 수 있다

---

.github/workflows/dev-cicd.yml
.github/workflows/test-cicd.yml

---
- 클라우드를 `GCP`에서 `AWS`로 이관하였습니다.
- 배포 서버 도메인 변경 및 GitHub Actions 스크립트를 일부 수정했습니다.
---
- Resolves : #139 
---

[chore] : 클라우드를 GCP -> AWS로 이관한다

---

deploy/deploy.sh

---
- CICD 결과를 디스코드 메세지로 전송한다
---
- Resolves : #147 
---

[feat] : CICD 결과를 디스코드 메세지로 전송한다

---

README.md
deploy/deploy.sh
src/main/java/side/onetime/service/EventCleanupScheduler.java
src/main/java/side/onetime/service/EventService.java
src/main/java/side/onetime/util/S3Util.java

---
- 리드미 수정 : 브랜치 규칙 & 시스템 아키텍처
- QR 디렉토리 추가
- S3 파일 삭제 기능 추가
---
- Resolves : #146 
---

[feat] : 이벤트 정기 삭제 시 S3에 있는 QR 이미지도 함께 삭제한다

---

src/main/java/side/onetime/auth/handler/OAuthLoginFailureHandler.java
src/main/java/side/onetime/auth/handler/OAuthLoginSuccessHandler.java
src/main/java/side/onetime/global/config/SecurityConfig.java

---
- 소셜 로그인 시, 성공 or 실패 여부를 반환한다.
- 실패 시 클라이언트에서 팝업 노출 후, 재로그인을 유도한다. (구현 예정)
---
- Resolves : #142 
---

[feat] : 소셜 로그인 실패 시 처리 로직을 추가한다

---

src/main/java/side/onetime/service/EventService.java

---
- 종료 조건을 변경하여 문제를 해결하였습니다.
---
- Resolves : #141 
---

[fix] : 가장 많이 되는 시간 6개를 찾을 시 반복문을 종료하도록 수정한다

---

src/main/java/side/onetime/dto/event/response/GetEventResponse.java
src/test/java/side/onetime/event/EventControllerTest.java

---
- 이벤트 조회 시, 응답에 이벤트 ID 필드를 추가하였습니다.
---
- Resolves : #155 
---

[feat] : 이벤트 조회 시, 응답에 이벤트 ID 필드를 추가한다

---

deploy/deploy.sh

---
- CICD 확인용으로 만들어 둔 디스코드 웹훅 링크로, 악의적으로 스팸 메세지를 수십~수백개를 보내는 것을 확인
- 처음에는 해프닝으로 생각했으나, URL이 해킹된 건지 계속해서 메세지가 전송됨
- 이에 URL을 환경변수 처리하여 해결하도록 함
---
- Resolves : #159 
---

[fix] : 디스코드 웹훅 URL을 환경변수 처리하여 공격을 방지한다

---

.github/workflows/prod-cicd.yaml
.github/workflows/test-cicd.yaml
src/main/java/side/onetime/controller/UserController.java
src/main/java/side/onetime/domain/User.java
src/main/java/side/onetime/dto/user/request/UpdateUserPolicyAgreementRequest.java
src/main/java/side/onetime/dto/user/response/GetUserPolicyAgreementResponse.java
src/main/java/side/onetime/global/common/status/SuccessStatus.java
src/main/java/side/onetime/service/UserService.java
src/test/java/side/onetime/configuration/ControllerTestConfig.java
src/test/java/side/onetime/user/UserControllerTest.java

---
- 유저 약관 동의 여부를 조회할 수 있습니다.
- 유저 약관 동의 여부를 수정할 수 있습니다.
---
- Resolves : #166 
---

[feat] : 유저 약관 동의 여부를 조회 및 수정할 수 있다

---

src/main/java/side/onetime/controller/UserController.java
src/main/java/side/onetime/domain/User.java
src/main/java/side/onetime/dto/user/request/UpdateUserSleepTimeRequest.java
src/main/java/side/onetime/dto/user/response/GetUserSleepTimeResponse.java
src/main/java/side/onetime/global/common/status/SuccessStatus.java
src/main/java/side/onetime/service/UserService.java
src/main/resources/static/docs/open-api-3.0.1.json
src/test/java/side/onetime/user/UserControllerTest.java

---
- 유저 수면 시간을 조회할 수 있습니다.
- 유저 수면 시간을 수정할 수 있습니다.
---
- Resolves : #168 
---

[feat] : 유저 수면 시간을 조회 및 수정할 수 있다

---

src/main/java/side/onetime/repository/custom/UserRepositoryImpl.java

---
- 유저 탈퇴 시, 쿼리 DSL 메서드에서 고정 스케줄을 삭제하지 않아 유저 탈퇴 시 오류가 발생했습니다.
- 고정 스케줄도 함께 삭제하도록 변경하여 문제를 해결하였습니다.
---
- Resolves : #192 
---

[fix] : 고정 스케줄도 삭제하도록 변경하여 문제를 해결한다

---

src/main/java/side/onetime/auth/handler/OAuthLoginSuccessHandler.java
src/main/java/side/onetime/controller/AdminUserController.java
src/main/java/side/onetime/domain/AdminUser.java
src/main/java/side/onetime/domain/enums/AdminStatus.java
src/main/java/side/onetime/dto/adminUser/request/LoginAdminUserRequest.java
src/main/java/side/onetime/dto/adminUser/request/RegisterAdminUserRequest.java
src/main/java/side/onetime/dto/adminUser/response/GetAdminUserProfileResponse.java
src/main/java/side/onetime/dto/adminUser/response/LoginAdminUserResponse.java
src/main/java/side/onetime/exception/status/AdminUserErrorStatus.java
src/main/java/side/onetime/exception/status/TokenErrorStatus.java
src/main/java/side/onetime/global/common/status/SuccessStatus.java
src/main/java/side/onetime/global/config/SecurityConfig.java
src/main/java/side/onetime/global/config/SwaggerConfig.java
src/main/java/side/onetime/repository/AdminUserRepository.java
src/main/java/side/onetime/repository/UserRepository.java
src/main/java/side/onetime/service/AdminUserService.java
src/main/java/side/onetime/service/TokenService.java
src/main/java/side/onetime/service/UserService.java
src/main/java/side/onetime/util/JwtUtil.java
src/main/resources/application.yaml
src/test/java/side/onetime/adminUser/AdminUserControllerTest.java

---
- 관리자 회원가입 API를 구현하였습니다.
- 관리자 로그인 API를 구현하였습니다.
- 관리자 프로필 조회  API를 구현하였습니다.
- 일부 불필요한 메서드와 파라미터를 제거하였습니다.
---
- Resolves : #196 
---

[feat] : 관리자는 회원가입 & 로그인 & 프로필 조회를 할 수 있다

---

src/main/java/side/onetime/controller/AdminUserController.java
src/main/java/side/onetime/domain/AdminUser.java
src/main/java/side/onetime/domain/enums/AdminStatus.java
src/main/java/side/onetime/dto/adminUser/request/UpdateAdminUserStatusRequest.java
src/main/java/side/onetime/dto/adminUser/response/AdminUserDetailResponse.java
src/main/java/side/onetime/exception/GlobalExceptionHandler.java
src/main/java/side/onetime/exception/status/AdminUserErrorStatus.java
src/main/java/side/onetime/global/common/status/SuccessStatus.java
src/main/java/side/onetime/service/AdminUserService.java
src/test/java/side/onetime/adminUser/AdminUserControllerTest.java

---
- 마스터 관리자를 추가하였습니다.
- 마스터 관리자는 전체 관리자 정보를 조회할 수 있습니다.
- 마스터 관리자는 특정 관리자의 권한을 수정할 수 있습니다.
- 요청 값이 ENUM에 맞지 않는 경우의 예외처리를 위해, `handleHttpMessageNotReadable`를 오버라이드하여 메서드를 구현하였습니다.
---
- Resolves : #198 
---

[feat] : 마스터 관리자는 관리자들을 조회하고 권한을 수정할 수 있다

---

src/main/java/side/onetime/controller/AdminUserController.java
src/main/java/side/onetime/global/common/status/SuccessStatus.java
src/main/java/side/onetime/service/AdminUserService.java
src/test/java/side/onetime/adminUser/AdminUserControllerTest.java

---
- 관리자 탈퇴 API를 구현하였습니다.
---
- Resolves : #200
---

[feat] : 관리자는 탈퇴할 수 있다

---

src/main/java/side/onetime/controller/AdminUserController.java
src/main/java/side/onetime/dto/adminUser/response/DashboardEvent.java
src/main/java/side/onetime/dto/event/response/GetParticipantsResponse.java
src/main/java/side/onetime/exception/status/AdminUserErrorStatus.java
src/main/java/side/onetime/global/common/status/SuccessStatus.java
src/main/java/side/onetime/repository/EventRepository.java
src/main/java/side/onetime/repository/custom/EventRepositoryCustom.java
src/main/java/side/onetime/repository/custom/EventRepositoryImpl.java
src/main/java/side/onetime/service/AdminUserService.java
src/main/java/side/onetime/service/EventService.java
src/main/java/side/onetime/util/NamingUtil.java
src/test/java/side/onetime/adminUser/AdminUserControllerTest.java

---
- 관리자는 모든 이벤트를 조회할 수 있습니다.
- 동적 쿼리를 사용하여, 특정 열을 대상으로 오름차순 or 내림차순 정렬할 수 있도록 구현하였습니다.
---
- Resolves : #202 
---

[feat] : 대시보드 이벤트 관리 정보를 조회할 수 있다

---

src/main/java/side/onetime/controller/AdminUserController.java
src/main/java/side/onetime/dto/adminUser/response/DashboardEvent.java
src/main/java/side/onetime/dto/adminUser/response/DashboardUser.java
src/main/java/side/onetime/exception/status/AdminUserErrorStatus.java
src/main/java/side/onetime/global/common/status/SuccessStatus.java
src/main/java/side/onetime/repository/EventParticipationRepository.java
src/main/java/side/onetime/repository/MemberRepository.java
src/main/java/side/onetime/repository/ScheduleRepository.java
src/main/java/side/onetime/repository/custom/EventParticipationRepositoryCustom.java
src/main/java/side/onetime/repository/custom/EventParticipationRepositoryImpl.java
src/main/java/side/onetime/repository/custom/EventRepositoryImpl.java
src/main/java/side/onetime/repository/custom/UserRepositoryCustom.java
src/main/java/side/onetime/repository/custom/UserRepositoryImpl.java
src/main/java/side/onetime/service/AdminUserService.java
src/test/java/side/onetime/adminUser/AdminUserControllerTest.java

---
- 관리자는 대시보드에서 전체 유저를 조회할 수 있습니다.
- 동적 쿼리를 활용하여, 특정 키워드에 대해서 오름차순 or 내림차순 정렬하여 반환하도록 구현했습니다.
- 대시보드 이벤트 조회 시, 참여자 수를 유저(로그인)로만 집계하던 문제를 해결하였습니다.
---
- Resolves : #203 
---

[feat] : 관리자는 대시보드에서 전체 유저를 조회할 수 있다

---

deploy/deploy.sh

---
- 배포 이후, 불필요한 도커 이미지를 제거합니다.
- 배포 이후, 24시간이 지난 도커 빌드 캐시를 제거합니다.
- 배포 타임 아웃을 120초로 연장하였습니다.
---
- Resolves : #208 
---

[feat] : 배포 이후 불필요한 도커 이미지 및 빌드 캐시를 정리한다

---

src/main/java/side/onetime/controller/EventController.java
src/main/java/side/onetime/controller/FixedController.java
src/main/java/side/onetime/controller/ScheduleController.java
src/main/java/side/onetime/controller/UserController.java
src/main/java/side/onetime/service/EventService.java
src/main/java/side/onetime/service/FixedScheduleService.java
src/main/java/side/onetime/service/ScheduleService.java
src/main/java/side/onetime/service/UserService.java
src/main/java/side/onetime/util/UserAuthorizationUtil.java
src/test/java/side/onetime/event/EventControllerTest.java
src/test/java/side/onetime/fixed/FixedControllerTest.java
src/test/java/side/onetime/schedule/ScheduleControllerTest.java
src/test/java/side/onetime/user/UserControllerTest.java

---
- 세션 밖에서 가져온 유저 객체를 활용해 Lazy 필드에 접근하며 `LazyInitializationException`이 발생하였습니다.
- `UserAuthorizationUtil` 클래스를 만든 후, 서비스단 트랜잭셔널 내에서 유저 객체를 가져오도록 변경하며 문제를 해결하였습니다.
- [작성 글](https://velog.io/@hsh111366/트러블슈팅-JwtFilter-문제-해결)
---
- Resolves : #213 
---

[fix] : LazyInitializationException을 해결한다

---

src/main/java/side/onetime/exception/status/TokenErrorStatus.java
src/main/java/side/onetime/global/filter/JwtFilter.java
src/main/java/side/onetime/global/interceptor/LoggingInterceptor.java
src/main/java/side/onetime/util/JwtUtil.java
src/main/resources/application-prod.yaml
src/main/resources/application-test.yaml

---
- shouldNotFilter 경로의 정규식이 잘못 설정되어, 필터를 타지 않아야 하는 요청까지 필터를 타는 문제가 존재했습니다.
- 정규식을 수정함으로써 문제를 해결하였습니다.
- 4xx 에러에 대해서도 예외 처리를 추가하였습니다.
---
- Ref : #213 
---

[fix] : shouldNotFilter 경로를 수정하여 문제를 해결한다

---

.github/workflows/test-cicd.yaml

---
- 기존에는 PR 이후 머지(Push)하는 과정에서도 배포가 1번 더 이루어지면서 불필요한 시간 소모가 있었습니다.
- Push에 대한 트리거를 제거하여 불필요한 배포를 줄이도록 변경하였습니다.
---
---

[feat] : Push에 대한 트리거를 제거하여 불필요한 배포를 줄인다

---

deploy/deploy.sh

---
- 방화벽 설정을 위해서 도커 컨테이너 포트포워딩을 제거하였습니다.
- 이에 따라 `docker-compose.yaml & deploy.sh & nginx` 설정 파일들을 수정하였습니다.
---
- Resolves : #224 
---

[feat] : 방화벽 설정을 위해서 도커 컨테이너 포트포워딩을 제거한다

---

README.md
src/main/java/side/onetime/exception/GlobalExceptionHandler.java

---
- 기존에는 전체 stack trace가 로깅되는 경우가 있어서, 로그를 보기가 불편한 점이 있었습니다.
- 때문에 Throw한 예외에 대해서는 전체 stack trace가 나오지 않도록 하여 해당 부분을 개선하였습니다.
- 리드미의 시스템 아키텍처 부분을 수정하였습니다.
---
- Resolves : #227 
---

[feat] : Throw한 예외에 대해서는 전체 stack trace가 나오지 않도록 한다

---

README.md
src/main/java/side/onetime/exception/GlobalExceptionHandler.java
src/main/java/side/onetime/util/JwtUtil.java

---
- 불필요한 로깅을 제거하였습니다.
---
- Resolves : #227 
---

[feat] : 불필요한 로깅을 제거한다

---

build.gradle
src/main/java/side/onetime/global/config/S3Config.java
src/main/java/side/onetime/util/S3Util.java

---
```bash
2025-05-19T21:45:46.384+09:00  WARN 20449 --- [           main] com.amazonaws.util.VersionInfoUtils      : The AWS SDK for Java 1.x entered maintenance mode starting July 31, 2024 and will reach end of support on December 31, 2025. For more information, see https://aws.amazon.com/blogs/developer/the-aws-sdk-for-java-1-x-is-in-maintenance-mode-effective-july-31-2024/
You can print where on the file system the AWS SDK for Java 1.x core runtime is located by setting the AWS_JAVA_V1_PRINT_LOCATION environment variable or aws.java.v1.printLocation system property to 'true'.
This message can be disabled by setting the AWS_JAVA_V1_DISABLE_DEPRECATION_ANNOUNCEMENT environment variable or …
```

[refactor] : AWS SDK for Java를 2.25.30 버전으로 업그레이드한다

---

src/main/java/side/onetime/repository/SelectionRepository.java
src/main/java/side/onetime/service/ScheduleService.java

---
- 이벤트에 첫 입장하는 경우에 최악의 경우 7~8초나 로딩을 기다려야하는 경우가 있었습니다.
- 이에 대해 파악해 보니, N+1 문제가 발생하고 있음을 알게 되었습니다.
- 이를 해결하기 위해서 fetch join을 적용하였습니다.
- 또한 중복 메서드를 분리함으로써 코드 가독성을 높였습니다.
- 결과적으로 98%의 성능 개선을 할 수 있었습니다.
---
- Ref : #233 
---
[작성한 블로그 글](https://velog.io/@hsh111366/OneTime-성능-개선일지-1-전체-스케줄-조회-API)

[feat] : 전체 스케줄 조회 API 성능 개선을 진행한다
